"""Tests for report modules: HTML, Markdown, JSON."""

from __future__ import annotations

import json
from pathlib import Path

from ai_secrets_guard.core.models import ProbeResult, ScanResult
from ai_secrets_guard.report.html import render_html, write_html
from ai_secrets_guard.report.json_report import render_json, write_json
from ai_secrets_guard.report.markdown import render_markdown, write_markdown

# ---------------------------------------------------------------------------
# HTML Report
# ---------------------------------------------------------------------------


class TestHtmlReport:
    def test_contains_executive_summary(self, sample_scan_result: ScanResult) -> None:
        html = render_html(sample_scan_result)
        assert "Executive Summary" in html

    def test_contains_risk_gauge_svg(self, sample_scan_result: ScanResult) -> None:
        html = render_html(sample_scan_result)
        assert "risk-gauge" in html
        assert "<svg" in html

    def test_contains_grade(self, sample_scan_result: ScanResult) -> None:
        html = render_html(sample_scan_result)
        assert "grade-display" in html

    def test_contains_top_findings(self, sample_scan_result: ScanResult) -> None:
        html = render_html(sample_scan_result)
        assert "Top Findings" in html
        assert "SEC-OPENAI-001" in html

    def test_contains_severity_cards(self, sample_scan_result: ScanResult) -> None:
        html = render_html(sample_scan_result)
        assert "severity-critical" in html
        assert "severity-high" in html

    def test_contains_finding_cards(self, sample_scan_result: ScanResult) -> None:
        html = render_html(sample_scan_result)
        assert "finding-card" in html
        assert "PI-IGNORE-001" in html
        assert "MCP-PERM-ALL" in html

    def test_finding_cards_have_code_snippets(self, sample_scan_result: ScanResult) -> None:
        html = render_html(sample_scan_result)
        assert "code-snippet" in html or "matched_text" not in html or "sk-t" in html

    def test_contains_owasp_section(self, sample_scan_result: ScanResult) -> None:
        html = render_html(sample_scan_result)
        assert "OWASP LLM Top 10" in html
        assert "LLM01" in html
        assert "LLM06" in html

    def test_contains_remediation(self, sample_scan_result: ScanResult) -> None:
        html = render_html(sample_scan_result)
        assert "Remediation Plan" in html

    def test_contains_footer(self, sample_scan_result: ScanResult) -> None:
        html = render_html(sample_scan_result)
        assert "ai-secrets-guard" in html
        assert "Generated by" in html

    def test_contains_version(self, sample_scan_result: ScanResult) -> None:
        html = render_html(sample_scan_result)
        assert "0.1.0" in html

    def test_contains_duration(self, sample_scan_result: ScanResult) -> None:
        html = render_html(sample_scan_result)
        assert "5.0s" in html

    def test_empty_findings_no_findings_message(self) -> None:
        result = ScanResult(project_path="/empty")
        html = render_html(result)
        assert "No findings" in html

    def test_with_probe_results(
        self,
        sample_scan_result: ScanResult,
        sample_probe_result: ProbeResult,
    ) -> None:
        html = render_html(sample_scan_result, probe=sample_probe_result)
        assert "Probe Results" in html
        assert "direct_override" in html
        assert "system_tag_injection" in html
        assert "Vulnerable" in html
        assert "Safe" in html
        assert "confidence-bar" in html

    def test_no_probe_section_without_probe(self, sample_scan_result: ScanResult) -> None:
        html = render_html(sample_scan_result)
        assert "Probe Results" not in html

    def test_self_contained_no_external_cdn(self, sample_scan_result: ScanResult) -> None:
        html = render_html(sample_scan_result)
        assert "cdn." not in html.lower()
        assert "unpkg.com" not in html.lower()

    def test_dark_theme(self, sample_scan_result: ScanResult) -> None:
        html = render_html(sample_scan_result)
        assert 'data-theme="dark"' in html
        assert "--bg-primary" in html

    def test_custom_title(self, sample_scan_result: ScanResult) -> None:
        html = render_html(sample_scan_result, title="Custom Report Title")
        assert "Custom Report Title" in html

    def test_write_creates_file(
        self,
        sample_scan_result: ScanResult,
        tmp_path: Path,
    ) -> None:
        out = write_html(sample_scan_result, tmp_path / "out" / "report.html")
        assert out.exists()
        assert out.stat().st_size > 0

    def test_write_with_probe(
        self,
        sample_scan_result: ScanResult,
        sample_probe_result: ProbeResult,
        tmp_path: Path,
    ) -> None:
        out = write_html(
            sample_scan_result,
            tmp_path / "report.html",
            probe=sample_probe_result,
        )
        content = out.read_text()
        assert "Probe Results" in content

    def test_collapsible_js_included(self, sample_scan_result: ScanResult) -> None:
        html = render_html(sample_scan_result)
        assert "finding-header" in html
        assert "<script>" in html


# ---------------------------------------------------------------------------
# JSON Report
# ---------------------------------------------------------------------------


class TestJsonReport:
    def test_is_valid_json(self, sample_scan_result: ScanResult) -> None:
        raw = render_json(sample_scan_result)
        data = json.loads(raw)
        assert isinstance(data, dict)

    def test_has_metadata(self, sample_scan_result: ScanResult) -> None:
        data = json.loads(render_json(sample_scan_result))
        meta = data["metadata"]
        assert meta["tool"] == "ai-secrets-guard"
        assert meta["version"] == "0.1.0"
        assert meta["project_path"] == "/test/project"
        assert meta["scan_id"] == "TEST001"
        assert "generated_at" in meta

    def test_has_score(self, sample_scan_result: ScanResult) -> None:
        data = json.loads(render_json(sample_scan_result))
        score = data["score"]
        assert "value" in score
        assert "grade" in score
        assert score["max"] == 10.0
        assert 0 <= score["value"] <= 10

    def test_has_summary(self, sample_scan_result: ScanResult) -> None:
        data = json.loads(render_json(sample_scan_result))
        summary = data["summary"]
        assert summary["CRITICAL"] == 2
        assert summary["HIGH"] == 1

    def test_has_scan_results(self, sample_scan_result: ScanResult) -> None:
        data = json.loads(render_json(sample_scan_result))
        scan = data["scan_results"]
        assert scan["total_findings"] == 3
        assert len(scan["findings"]) == 3
        f0 = scan["findings"][0]
        assert "rule_id" in f0
        assert "severity" in f0
        assert "title" in f0
        assert "description" in f0

    def test_findings_sorted_by_severity(self, sample_scan_result: ScanResult) -> None:
        data = json.loads(render_json(sample_scan_result))
        severities = [f["severity"] for f in data["scan_results"]["findings"]]
        assert severities[0] == "CRITICAL"

    def test_has_probe_results_empty(self, sample_scan_result: ScanResult) -> None:
        data = json.loads(render_json(sample_scan_result))
        probe = data["probe_results"]
        assert probe["total"] == 0
        assert probe["vulnerable"] == 0
        assert probe["responses"] == []

    def test_has_probe_results_with_data(
        self,
        sample_scan_result: ScanResult,
        sample_probe_result: ProbeResult,
    ) -> None:
        data = json.loads(render_json(sample_scan_result, probe=sample_probe_result))
        probe = data["probe_results"]
        assert probe["total"] == 3
        assert probe["vulnerable"] == 2
        assert probe["target_url"] == "https://api.test.com/v1/chat"
        resp0 = probe["responses"][0]
        assert "payload_name" in resp0
        assert "is_vulnerable" in resp0
        assert "confidence" in resp0
        assert "evidence" in resp0
        assert "technique" in resp0

    def test_has_owasp_coverage(self, sample_scan_result: ScanResult) -> None:
        data = json.loads(render_json(sample_scan_result))
        owasp = data["owasp_coverage"]
        assert "covered" in owasp
        assert "items" in owasp
        assert len(owasp["items"]) == 10
        for item in owasp["items"].values():
            assert "title" in item
            assert "covered" in item

    def test_has_remediation(self, sample_scan_result: ScanResult) -> None:
        data = json.loads(render_json(sample_scan_result))
        assert "remediation" in data
        assert isinstance(data["remediation"], list)
        assert len(data["remediation"]) > 0

    def test_empty_scan(self) -> None:
        result = ScanResult(project_path="/empty")
        data = json.loads(render_json(result))
        assert data["scan_results"]["total_findings"] == 0
        assert data["score"]["value"] == 0.0
        assert data["score"]["grade"] == "A"

    def test_write_creates_file(
        self,
        sample_scan_result: ScanResult,
        tmp_path: Path,
    ) -> None:
        out = write_json(sample_scan_result, tmp_path / "report.json")
        assert out.exists()
        data = json.loads(out.read_text())
        assert "metadata" in data

    def test_write_with_probe(
        self,
        sample_scan_result: ScanResult,
        sample_probe_result: ProbeResult,
        tmp_path: Path,
    ) -> None:
        out = write_json(
            sample_scan_result,
            tmp_path / "report.json",
            probe=sample_probe_result,
        )
        data = json.loads(out.read_text())
        assert data["probe_results"]["total"] == 3


# ---------------------------------------------------------------------------
# Markdown Report
# ---------------------------------------------------------------------------


class TestMarkdownReport:
    def test_has_title(self, sample_scan_result: ScanResult) -> None:
        md = render_markdown(sample_scan_result)
        assert "# Security Scan Report" in md

    def test_has_shields_badges(self, sample_scan_result: ScanResult) -> None:
        md = render_markdown(sample_scan_result)
        assert "img.shields.io" in md

    def test_has_risk_score_badge(self, sample_scan_result: ScanResult) -> None:
        md = render_markdown(sample_scan_result)
        assert "risk_score" in md

    def test_has_owasp_badge(self, sample_scan_result: ScanResult) -> None:
        md = render_markdown(sample_scan_result)
        assert "OWASP_LLM" in md

    def test_has_severity_badges(self, sample_scan_result: ScanResult) -> None:
        md = render_markdown(sample_scan_result)
        assert "critical" in md.lower()

    def test_has_metadata(self, sample_scan_result: ScanResult) -> None:
        md = render_markdown(sample_scan_result)
        assert "/test/project" in md
        assert "TEST001" in md
        assert "5.0s" in md

    def test_has_grade(self, sample_scan_result: ScanResult) -> None:
        md = render_markdown(sample_scan_result)
        assert "Grade **" in md

    def test_has_summary_table(self, sample_scan_result: ScanResult) -> None:
        md = render_markdown(sample_scan_result)
        assert "| Severity | Count |" in md
        assert "CRITICAL" in md

    def test_has_findings_table(self, sample_scan_result: ScanResult) -> None:
        md = render_markdown(sample_scan_result)
        assert "| Severity | Rule | Title | Location |" in md
        assert "SEC-OPENAI-001" in md
        assert "PI-IGNORE-001" in md

    def test_has_collapsible_details(self, sample_scan_result: ScanResult) -> None:
        md = render_markdown(sample_scan_result)
        assert "<details>" in md
        assert "<summary>" in md
        assert "</details>" in md
        assert "Detailed Findings" in md

    def test_details_contain_finding_info(self, sample_scan_result: ScanResult) -> None:
        md = render_markdown(sample_scan_result)
        assert "**Rule:**" in md
        assert "**Description:**" in md

    def test_has_owasp_checklist(self, sample_scan_result: ScanResult) -> None:
        md = render_markdown(sample_scan_result)
        assert "OWASP LLM Top 10 Coverage" in md
        assert "LLM01" in md
        assert "- [x]" in md or "- [ ]" in md

    def test_has_remediation(self, sample_scan_result: ScanResult) -> None:
        md = render_markdown(sample_scan_result)
        assert "Remediation Plan" in md

    def test_empty_result_no_issues(self) -> None:
        result = ScanResult(project_path="/empty")
        md = render_markdown(result)
        assert "No security issues" in md

    def test_custom_title(self, sample_scan_result: ScanResult) -> None:
        md = render_markdown(sample_scan_result, title="My Custom Report")
        assert "# My Custom Report" in md

    def test_with_probe_results(
        self,
        sample_scan_result: ScanResult,
        sample_probe_result: ProbeResult,
    ) -> None:
        md = render_markdown(sample_scan_result, probe=sample_probe_result)
        assert "Probe Results" in md
        assert "direct_override" in md
        assert "Vulnerable" in md
        assert "Safe" in md

    def test_no_probe_section_without_probe(self, sample_scan_result: ScanResult) -> None:
        md = render_markdown(sample_scan_result)
        assert "Probe Results" not in md

    def test_write_creates_file(
        self,
        sample_scan_result: ScanResult,
        tmp_path: Path,
    ) -> None:
        out = write_markdown(sample_scan_result, tmp_path / "report.md")
        assert out.exists()
        content = out.read_text()
        assert "CRITICAL" in content

    def test_write_with_probe(
        self,
        sample_scan_result: ScanResult,
        sample_probe_result: ProbeResult,
        tmp_path: Path,
    ) -> None:
        out = write_markdown(
            sample_scan_result,
            tmp_path / "report.md",
            probe=sample_probe_result,
        )
        content = out.read_text()
        assert "Probe Results" in content

    def test_finding_location_with_line(self, sample_scan_result: ScanResult) -> None:
        md = render_markdown(sample_scan_result)
        assert "config.py:10" in md

    def test_finding_location_without_line(self, sample_scan_result: ScanResult) -> None:
        md = render_markdown(sample_scan_result)
        assert ".cursor/mcp.json`" in md

    def test_matched_text_in_details(self, sample_scan_result: ScanResult) -> None:
        md = render_markdown(sample_scan_result)
        assert "sk-t***BlbJ" in md
